#!/bin/bash

# See also https://github.com/davidbrewer/xmonad-ubuntu-conf
# http://beginners-guide-to-xmonad.readthedocs.io/intro.html

export GTK2_RC_FILES="$HOME/.xmonad/gtkrc-2.0"

# Load resources
xrdb -merge .Xresources

# Start compositing to support transparency. You can omit this
# if you prefer not to use any transparency, but it is likely to cause
# ugly black fringing with some programs such as synapse that expect
# transparency support.
xcompmgr -n &

# Set background
nitrogen --restore &

# Displays
xrandr --output "DP-1" --auto --primary
xrandr | grep 'DP-2 connected' | ifne xrandr --output DP-2 --auto --left-of DP-1

# Run the gnome-keyring-daemon to avoid issues you otherwise may encounter
# when using gnome applications which expect access to the keyring, such
# as Empathy. This prevents prompts you may otherwise get for invalid
# certificates and the like.
gnome-keyring-daemon --start --components=gpg,pkcs11,secrets,ssh

exec xmonad
