#!/bin/sh

# Util functions
function is_installed() {
  command -v $1 > /dev/null
}

# Set up oh-my-zsh
if [ ! -e ~/.oh-my-zsh ]; then
    sh -c "$(curl -fsSL https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
fi

# Set up vim-bundles
if [ ! -e $HOME/.vim/autoload/plug.vim ]; then
  curl -fLo $HOME/.vim/autoload/plug.vim --create-dirs \
      https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
fi
vim -u $HOME/.vimrc.bundles +PlugInstall +PlugClean! +qa -

if is_installed "brew" && [ -e ~/.Brewfile ]; then
  brew bundle install --file=~/.Brewfile --verbose
fi
