#!/bin/sh

# Util functions
function is_installed() {
  command -v $1 > /dev/null
}

# Set up oh-my-zsh
# if [ ! -e ~/.oh-my-zsh ]; then
#     sh -c "$(curl -fsSL https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
# fi

# Set up vim-bundles
if [ ! -e $HOME/.vim/autoload/plug.vim ]; then
  curl -fLo $HOME/.vim/autoload/plug.vim --create-dirs \
      https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
fi
nvim +PlugInstall +PlugClean! +qa -

if [ ! -e $HOME/.local/share/nvim/site/pack/packer/start/packer.nvim ]; then
  git clone https://github.com/wbthomason/packer.nvim $HOME/.local/share/nvim/site/pack/packer/start/packer.nvim
fi

if is_installed "brew" && [ -e ~/.Brewfile ]; then
  brew bundle install --file=~/.Brewfile --verbose
fi

if [ ! -e ~/.tmux/plugins/tpm ]; then
  git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
fi

~/.dotfiles/.base16/install.sh update
